apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  # estos valores están en base64 y deben coincidir con los de postgres
  DATABASE_USER: bXl1c2Vy
  DATABASE_PASSWORD: bXlwYXNzd29yZA==