apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
  labels:
    app: django-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      initContainers:
        - name: django-migrations
          image: ghcr.io/jar3/django-todo-app:latest
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
      containers:
        - name: django-todo
          image: ghcr.io/jar3/django-todo-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10