apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP