name: Build and share Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
<<<<<<< HEAD
      - 

=======
      - 'manage.py'
      - 'requirements.txt'
      - 'django_project/**'
      - 'django_project/**'
      - 'todo_app/**'
      - 'venv/**'
      
>>>>>>> 16318eb40d34670d6f046c3b4ff60740a77e29ff
jobs:
  build-and-share:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest