apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: django_todo   # Reemplaza con el nombre de tu base de datos
  POSTGRES_USER: myuser     # Reemplaza con el nombre de usuario
  POSTGRES_PORT: "5432"
