apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi # Ajusta según lo que necesites
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres" # Ajusta según tu sistema
